development:
  adapter: sqlite3
  encoding: utf8
  database: db/development.sqlite3

test:
  adapter: sqlite3
  encoding: utf8
  database: db/test.sqlite3

production:
  adapter: postgresql
  encoding: utf8
  database: grokphoto-production